[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor -p /dev/tty.usbmodem311401"
# runner = "espflash flash --monitor"


[env]
ESP_LOG = "debug"
# SSID = "network"
# PASSWORD = "password"

[build]
rustflags = ["-C", "link-arg=-nostartfiles"]

target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["alloc", "core"]
